### ISSUE TITLE
Add CI building

### ISSUE THREAD

**Issue by neothemachine** [JPMoresmau/BuildWrapper#50]
It would be nice if Travis CI is used for reproducible testing/building of this library against multiple ghc versions. See https://github.com/adp-multi/adp-multi/blob/master/.travis.yml for some inspiration. If you need help, just ask.

**Comment by JPMoresmau** [comment]
Since I'm the only contributor and everybody else does nothing but send issues, I don't see the interest.

**Comment by neothemachine** [comment]
In most of my projects I'm also the only contributor. Of course, CI is useful for pull requests etc. but in my mind it is also useful for ownself. You just *know* that another machine that your own could successfully build and run your library.

How about... you flip the switch in Travis CI and I do the rest?
